### ISSUE TITLE
複数の「img」フォルダーの画像ファイル名が文字化けしている

### ISSUE THREAD

**Issue by yamatoya** [unity3d-jp/FirstTutorial#2]
「img」フォルダーの画像ファイル名が文字化けしているため、wikiからその文字化けしたファイル名を指定しても画像が表示されません。

https://github.com/unity3d-jp/FirstTutorial/wiki
の2つめの画像。（その他多数）

「ゲーム画面.png」
エディターなどで表示すると、ゲが2文字になっています。
（Windowsで確認）

wikiはForkしても内容がForkされなかったので、プルリクできなかったのでissueでの報告にしました。

**Comment by tsubaki** [comment]
ご指摘ありがとうございます。
UTF-8-Macの仕様を見落としておりました。
